export const DOCUMENT_TYPE_OPTIONS = [
  'ITAHC',
  'VETERINARY_HEALTH_CERTIFICATE',
  'AIR_WAYBILL',
  'IMPORT_PERMIT',
  'LETTER_OF_AUTHORITY',
  'COMMERCIAL_INVOICE',
  'SEA_WAYBILL',
  'RAIL_WAYBILL',
  'BILL_OF_LADING',
  'CATCH_CERTIFICATE',
  'LABORATORY_SAMPLING_RESULTS_FOR_AFLATOXIN',
  'HEALTH_CERTIFICATE',
  'JOURNEY_LOG',
  'OTHER'
]

export const ATTACHMENT_TYPE_OPTIONS = [
  'PDF',
  'DOC',
  'DOCX',
  'JPG',
  'JPEG',
  'PNG',
  'XLS',
  'XLSX'
]
