import {
  grossVolume,
  grossVolumeUnit,
  totalGrossWeight
} from './sections/additional-details.js'
import { commodityInputMethod } from './sections/commodities/input-method.js'
import {
  commodityLines,
  commoditySelection,
  controlledAtmosphereContainer,
  finishedOrPropagated,
  intendedForFinalUsers,
  netWeight,
  numberOfPackages,
  packageType,
  quantity,
  quantityType,
  testAndTrial
} from './sections/commodities/lines.js'
import {
  eppoCode,
  genusAndSpecies,
  species,
  speciesId
} from './sections/commodities/species.js'
import {
  varieties,
  variety,
  varietyClass
} from './sections/commodities/varieties.js'
import {
  responsiblePersonEmail,
  responsiblePersonName,
  responsiblePersonTelephone
} from './sections/contacts.js'
import {
  countryOfConsignment,
  countryOfOrigin,
  internalReference
} from './sections/origin.js'
import {
  commonTransitConvention,
  movementReferenceNumber,
  usingGvms
} from './sections/goods-movement.js'
import {
  accompanyingDocuments,
  documentReference,
  documentType,
  issueDate
} from './sections/documents.js'
import { reasonForImport } from './sections/purpose.js'
import {
  consignorAddressLine1,
  consignorAddressLine2,
  consignorAddressLine3,
  consignorCity,
  consignorCountry,
  consignorEmail,
  consignorName,
  consignorPostcode,
  consignorTelephone,
  destinationAddressLine1,
  destinationAddressLine2,
  destinationAddressLine3,
  destinationCity,
  destinationCountry,
  destinationName,
  destinationPostcode,
  destinationSameAsConsignee,
  packerAddressLine1,
  packerAddressLine2,
  packerAddressLine3,
  packerCity,
  packerCountry,
  packerName,
  packerPostcode
} from './sections/parties.js'
import {
  arrivalDate,
  arrivalTime,
  borderControlPost,
  containerNumber,
  containers,
  inspectionPremises,
  meansOfTransport,
  officialSeal,
  sealNumber,
  transportDocumentReference,
  transportIdentification,
  usesContainers
} from './sections/transport.js'

export {
  totalGrossWeight,
  grossVolume,
  grossVolumeUnit,
  accompanyingDocuments,
  documentType,
  documentReference,
  issueDate,
  commodityInputMethod,
  commodityLines,
  commoditySelection,
  numberOfPackages,
  packageType,
  quantity,
  quantityType,
  netWeight,
  controlledAtmosphereContainer,
  finishedOrPropagated,
  intendedForFinalUsers,
  testAndTrial,
  species,
  eppoCode,
  genusAndSpecies,
  speciesId,
  varieties,
  variety,
  varietyClass,
  responsiblePersonName,
  responsiblePersonEmail,
  responsiblePersonTelephone,
  countryOfConsignment,
  countryOfOrigin,
  internalReference,
  reasonForImport,
  arrivalDate,
  arrivalTime,
  borderControlPost,
  containerNumber,
  containers,
  inspectionPremises,
  meansOfTransport,
  officialSeal,
  sealNumber,
  transportDocumentReference,
  transportIdentification,
  usesContainers,
  commonTransitConvention,
  movementReferenceNumber,
  usingGvms,
  destinationSameAsConsignee,
  destinationName,
  destinationAddressLine1,
  destinationAddressLine2,
  destinationAddressLine3,
  destinationCity,
  destinationPostcode,
  destinationCountry,
  packerName,
  packerAddressLine1,
  packerAddressLine2,
  packerAddressLine3,
  packerCity,
  packerPostcode,
  packerCountry,
  consignorName,
  consignorAddressLine1,
  consignorAddressLine2,
  consignorAddressLine3,
  consignorCity,
  consignorPostcode,
  consignorTelephone,
  consignorCountry,
  consignorEmail
}

export const obligations = [
  countryOfOrigin,
  countryOfConsignment,
  internalReference,
  reasonForImport,
  commodityInputMethod,
  commodityLines,
  commoditySelection,
  numberOfPackages,
  packageType,
  quantity,
  quantityType,
  netWeight,
  controlledAtmosphereContainer,
  finishedOrPropagated,
  intendedForFinalUsers,
  testAndTrial,
  species,
  eppoCode,
  genusAndSpecies,
  speciesId,
  varieties,
  variety,
  varietyClass,
  responsiblePersonName,
  responsiblePersonEmail,
  responsiblePersonTelephone,
  totalGrossWeight,
  grossVolume,
  grossVolumeUnit,
  accompanyingDocuments,
  documentType,
  documentReference,
  issueDate,
  borderControlPost,
  inspectionPremises,
  meansOfTransport,
  transportIdentification,
  transportDocumentReference,
  arrivalDate,
  arrivalTime,
  usesContainers,
  containers,
  containerNumber,
  sealNumber,
  officialSeal,
  commonTransitConvention,
  movementReferenceNumber,
  usingGvms,
  destinationSameAsConsignee,
  destinationName,
  destinationAddressLine1,
  destinationAddressLine2,
  destinationAddressLine3,
  destinationCity,
  destinationPostcode,
  destinationCountry,
  packerName,
  packerAddressLine1,
  packerAddressLine2,
  packerAddressLine3,
  packerCity,
  packerPostcode,
  packerCountry,
  consignorName,
  consignorAddressLine1,
  consignorAddressLine2,
  consignorAddressLine3,
  consignorCity,
  consignorPostcode,
  consignorTelephone,
  consignorCountry,
  consignorEmail
]

export const groups = obligations.filter((obligation) =>
  obligations.some((other) => other.within === obligation)
)

export const policy = {
  systemPopulated: [],
  enforcedAtContinue: ['countryOfOrigin', 'commoditySelection'],
  maxEntriesFrom: {},
  systemAnswerKeys: ['referenceNumber']
}
