export const copy = {
  title: 'Goods movement services',
  caption: 'Transport',
  ctc: {
    legend:
      'Are you using the Common Transit Convention (CTC) to move goods, such as to a control point?',
    hint: 'If yes, you must provide the Movement Reference Number (MRN) that will have been generated by NCTS.',
    options: {
      ADD_MRN_NOW: 'Yes – add MRN now',
      ADD_MRN_LATER: 'Yes – add MRN later',
      NO: 'No'
    }
  },
  mrn: {
    label: 'Movement Reference Number (MRN)',
    hint: 'It is 18 characters, starting with 2 numbers, a 2-letter country code then 14 letters and numbers. For example, 24GB123456789AB012.'
  },
  ctcDetails: {
    summary: 'What is the CTC?',
    intro:
      'The Common Transit Convention (CTC) is a customs procedure that allows you to quickly move goods between countries in:',
    bullets: ['the UK', 'the EU', 'other CTC countries'],
    benefits:
      "It can help reduce the number of customs declarations you'll need to complete and you won't have to pay charges until you end the movement.",
    stepsIntro: 'To move your goods using the CTC, you need to:',
    steps: [
      'check if you can use it',
      'find out how to use it to move goods',
      'plan your route before you use it'
    ],
    linkText:
      'Find out more about using transit to move goods (opens in new tab)'
  },
  gvms: {
    legend: 'Will the transport use the Goods Vehicle Movement Service (GVMS)?',
    options: { yes: 'Yes', no: 'No' }
  },
  gvmsDetails: {
    summary: 'What is the GVMS?',
    paragraphs: {
      intro: 'GVMS helps to speed up customs clearance at some UK ports.',
      stepsIntro: 'To move your goods, you need to:',
      gmr: 'The GMR is a single reference that brings together multiple declarations. Without it, you cannot move your goods through UK ports which use the GVMS and you may face delays.',
      driver:
        'The driver must check the GVMS to find out if an inspection is required before they disembark.'
    },
    links: {
      portsList: 'Find out which ports use the GVMS (opens in new tab)',
      register: 'Register for the GVMS (opens in new tab)',
      gmr: 'Get a goods movement reference (GMR) (opens in new tab)'
    }
  },
  errors: {
    commonTransitConventionRequired:
      'Select if using the Common Transit Convention (CTC)',
    movementReferenceNumberInvalid: 'Enter a valid Movement Reference Number',
    usingGvmsRequired:
      'Select if using the Goods Vehicle Movement Service (GVMS)'
  }
}
